---
title: "Experience"
toc: false
---

Throughout my academic career, I have had the pleasure of managing and undergoing many intensive projects. Below are just a few of my accomplishments.

## Project 1
This is a project that analyzes drone strikes and how detrimental they are to civilian casualties. This was done with a team and we constructed geospatial heatmaps alongside a linear regression model to better understand how variables such as president and geographic location can impact casualties.  
Please read:  [Project](project1.pdf)  
Here are the slides as well:  [Slides](slides.pdf)

## Project 2
This is a project that took 23-24 NBA season data and built a model to help predict future wins. It was done by creating new variables to represent the home games and by weighing other variables to better fit the models. Five models were tested and trained to see which worked best, and Quadratic Discriminant Analysis (QDA) was the best suited for the data.  
Please read: [NBA Project](editedproj2.pdf)

## Github
Here is a link to my [personal github](https://github.com/brandon3210)

## Daily Bruin
Alongside my statistical and analytical abilities, I also work as a long-time staff member of the Daily Bruin outreach team, where I conduct surveys, workshops, and presentations. I also help with recruitment, internal and external matters, and social media. It has given me a well-rounded skill set with time management, people management, and overall communication skills.

## Personal Selling
I also have experience managing my own storefront and selling my own products. I handle listing, selling, customer service, product management, shipping, and handling all by myself in order to make this a fruitful and thriving side job. It has taught me a lot about how to deal with customers and managing my own inventory.